---

- name: set facts for use later
  include_tasks: tools/set_facts.yml

- name: create bashrcd
  include_tasks: tools/bashrcd.yml

- name: set shell env var
  include_tasks: tools/shell_env_var.yml

- name: set ssh agent
  include_tasks: tools/ssh_agent.yml

- name: install terraform
  include_tasks: tools/terraform.yml

- name: install docker
  include_tasks: tools/docker.yml

- name: install gh cli
  include_tasks: tools/gh_cli.yml

- name: install lastpass-cli
  include_tasks: tools/lastpass-cli.yml
