---

- name: set facts for use later
  include_tasks: tools/set_facts.yml

- name: create bash_profile
  include_tasks: tools/bash_profile.yml

- name: install terraform
  include_tasks: tools/terraform.yml

- name: install docker
  include_tasks: tools/docker.yml

- name: install gh cli
  include_tasks: tools/gh_cli.yml

- name: install lastpass-cli
  include_tasks: tools/lastpass-cli.yml
