---
- name: Ensure apt_keys are present before actions
  ansible.builtin.include_tasks: tools/00_apt_keys.yml

- name: set facts for use later
  include_tasks: tools/set_facts.yml

- name: customize user shell env
  include_tasks: user-env/shell_env.yml

- name: install terraform
  include_tasks: tools/terraform.yml

- name: install docker
  include_tasks: tools/docker.yml

- name: install gh cli
  include_tasks: tools/gh_cli.yml

- name: install aqua cli
  ansible.builtin.include_tasks: tools/aqua/aqua_cli.yml

- name: install lastpass-cli
  include_tasks: tools/lastpass-cli.yml

- name: ensure global tools are installed via https://github.com/Groupe-Hevea/tools-aquaproj
  ansible.builtin.include_tasks: tools/aqua/global_tools.yml
