---

- name: install required tools
  hosts: localhost
  become: yes
  vars:
    docker_users: ["{{ lookup('env', 'USER') }}"]
  vars_prompt:
    - name: github_token
      prompt: What is your github_token?
      private: false
  roles:
    - developer
