- name: add github cli apt key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present

- name: add hashicorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
