---

- name: add bashrc.d directory feature
  ansible.builtin.blockinfile:
    path:  "/etc/bash.bashrc"
    block: |
      # Taken from https://github.com/Groupe-Hevea/puppet-config/blob/master/modules/bash/templates/bashrc.erb
      # Load user's .bash.rc.d/
      if [ -d ~/.bashrc.d ]; then
        for file in ~/.bashrc.d/*.bashrc; do
          [ -e "$file" ] || continue
          source "$file"
        done
      fi

- name: ensure bashrc.d exists
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USER') }}/.bashrc.d"
    state: directory
    mode: '0755'
