---

- name: ensure obsolete packages are absent
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
    purge: yes

- name: ensure dependencies are installed
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
    update_cache: yes

- name: add docker apt fingerprint
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
    update_cache: yes

- name: ensure docker group exists
  group:
    name: docker
    state: present

- name: add users to docker group
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  with_items: "{{ docker_users }}"
  #notify: restart docker daemon

- name: specify docker daemon.json
  ansible.builtin.copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: /etc/docker/daemon.json

# docker compose
- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

## Start docker at startup :
# Windows 10
- name: Start docker at startup - Windows 10
  ansible.builtin.blockinfile:
    path: "/home/{{ lookup('env', 'USER') }}/.bash_profile"
    block: |
      #Start docker at startup
      wsl.exe -u root -e sh -c "service docker status || service docker start"
    state: present
  when: winver == "10"

# Windows 11
- name: Ensure wsl.conf exists - Windows 11
  ansible.builtin.copy:
    content: "[boot]\n"
    dest: "/etc/wsl.conf"
    force: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: winver == "11"

- name: Start docker at startup - Windows 11
  ansible.builtin.lineinfile:
    path: "/etc/wsl.conf"
    line: command = "service docker start"
    state: present
    insertafter: '[boot]'
  when: winver == "11"

- name: Delete old startup for Windows 10 - Windows 11
  ansible.builtin.blockinfile:
    path: "/home/{{ lookup('env', 'USER') }}/.bash_profile"
    block: |
      #Start docker at startup
      wsl.exe -u root -e sh -c "service docker status || service docker start"
    state: absent
  when: winver == "11"
