---

- name: Get Windows Version
  shell: /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe -c "(Get-CimInstance Win32_OperatingSystem).Caption -replace '[^\d]'"
  register: winver
  changed_when: false
  when: winver is undefined

- name: Set fact winver with associated windows version (10, 11, ...)
  set_fact:
    winver: "{{ winver.stdout }}"

- name: debug winver
  debug:
    var: winver
