---

- name: enable ssh agent
  ansible.builtin.copy:
    content: |
      # Taken from https://github.com/Groupe-Hevea/puppet-config/blob/master/modules/account/templates/ssh-agent.bashrc.erb
      # Enable ssh agent
      ssh-add -l &>/dev/null
      if [[ "$?" == 2 ]]; then
        eval $(ssh-agent) >/dev/null
      fi

      ssh-add -l &>/dev/null
      if [[ "$?" == 1 ]]; then
        ssh-add ~/.ssh/id_rsa &>/dev/null
      fi
    dest: "/home/{{ lookup('env', 'USER') }}/.bashrc.d/ssh_agent.bashrc"
    mode: '0644'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
