---

- name: enable ssh agent
  ansible.builtin.copy:
    content: |
      # Enable ssh agent
      if [ -z "$(pgrep ssh-agent)" ]; then
        rm -rf /tmp/ssh-*
        eval $(ssh-agent -s)
        ssh-add
      else
        export SSH_AGENT_PID=$(pgrep ssh-agent)
        export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name agent.*)
      fi
    dest: "/home/{{ lookup('env', 'USER') }}/.bashrc.d/ssh_agent.bashrc"
    mode: '0644'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
