- name: Script to update aqua global tools to latest version each login time
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash -eu
      # Update aqua global tools to latest version
      mkdir -p $HOME/.config/aqua
      git -C $HOME/.config/aqua init 2>/dev/null 1>/dev/null
      git -C $HOME/.config/aqua remote add -f origin https://github.com/Groupe-Hevea/tools-aquaproj.git 2>/dev/null 1>/dev/null
      git -C $HOME/.config/aqua config core.sparseCheckout true
      echo "aqua-config/*" > $HOME/.config/aqua/.git/info/sparse-checkout
      git -C $HOME/.config/aqua reset --hard HEAD 2>/dev/null 1>/dev/null
      git -C $HOME/.config/aqua pull origin master 2>/dev/null 1>/dev/null
      export AQUA_GLOBAL_CONFIG="$HOME/.config/aqua/aqua-config/all.yaml:${AQUA_GLOBAL_CONFIG:-}"
      aqua i -l -a
    dest: "/home/{{ lookup('env', 'USER') }}/.rc.d/99-aqua_global_tools.sh"
    mode: '0644'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
