- name: unprotect resolv.conf
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    attributes: -i

- name: generate resolv.conf and protect it
  become: true
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    attributes: +i
